### ISSUE TITLE
Set up documentation tool for install & configuration guides

### ISSUE THREAD

**Issue by Kisgus** [openbot-tech/core#12]
# Decide on tool

- [x] Decide on which tool to use such as [readthedocs](https://readthedocs.org/) / [0x documentation](https://0x.org/wiki#Community-Resources) or [Gekko documentation](https://gekko.wizb.it/docs/installation/installing_gekko.html)

# Implement

- [x] Merge the content of readme.md of openbot/core into this tool and list it as a "Documentation" tab on https://openbot.tech/#/

**Comment by seichris** [comment]
https://www.gitbook.com is pretty common

**Comment by Kisgus** [comment]
Done, ty @seichris 

https://openbot.gitbook.io/project/
