### ISSUE TITLE
Website v2

### ISSUE THREAD

**Issue by Kisgus** [openbot-tech/core#17]
## Mockup

https://www.figma.com/file/JFnuC7hohQ9wHSDcT69dMm67/openbot-v2

## Video

- [x] Backtesting video

https://drive.google.com/open?id=1K86JSdWerh80rF8PAxnDAuyeTdAJ5s3h

## First implementation

- [x] Done, live at https://openbot.tech/

## Second implementation

- [x] Done, live at https://openbot.tech/

**Comment by Kisgus** [comment]
# Feedback

## Main Navigation bar

- [x] Change tabs to below text

- [x] Delete **Documentation** tab as this will be included in **Install** that will link to gitbook

- [x] Change the page name sections from "Contribute" & "Vision" to "Strategies", "Governance"

- [x] Make "Features", "Strategies", "Governance" drop down to the respective pages on the site

- [x] Make "Install" a call-to-action by putting a button style around it

![Screen Shot 2019-03-10 at 1 05 54 PM](https://user-images.githubusercontent.com/18598519/54084787-7f533d00-4335-11e9-936f-fb83f3e7044b.png)


## Buttons

- Change from current style to field out black style like below

![Screen Shot 2019-03-10 at 1 19 39 PM](https://user-images.githubusercontent.com/18598519/54084891-4fa53480-4337-11e9-8f23-f0572e07bbcf.png)



## Links

- [x] **Gitcoin bounty** button links to https://github.com/openbot-tech/core/issues?utf8=%E2%9C%93&q=label%3A%22help+wanted%22

- [x] **Submit strategy** button links to https://github.com/openbot-tech/core/blob/master/src/core/strategy/strategies/TEMPLATE/index.js

- [x] **Vision paper** button links to https://docs.google.com/document/d/1Lwe9McxjwQhRvfU2domiRhuSC0pCJ3uLLh-xkARFePM/edit?usp=sharing

**Comment by seichris** [comment]
fixed all but the responsiveness.

responsiveness would be easy with bootstrap, but i don't get why react-bootstrap doesn't work

**Comment by Kisgus** [comment]
Thanks @seichris please see next batch of additions:

## Video / Picture

- [x] Embed the backtesting sample to replace the current chat picture: https://www.youtube.com/watch?v=Dg46tX_ms7Y&feature=youtu.be

## Text Edits

- [x] Change text in "Gitcoin Bounty" button to "Join Competition"
- [x] Change "Work in progress" to "Modular architecture" with subtext to "We plan to also support market-making, arbitrage and dedicated DeFi strategies"

![Screen Shot 2019-03-11 at 12 46 08 PM](https://user-images.githubusercontent.com/18598519/54121817-b7bd4e80-43fb-11e9-927e-418514d95b62.png)

## Social media


- [x] Put in Twitter logo in the bottom of the page

![Group 2](https://user-images.githubusercontent.com/18598519/54122191-a7f23a00-43fc-11e9-8e8a-557220479b2e.png)

- [x] Put in Medium logo in the buttom of the site

- [x]  Link medium to https://medium.com/openbot-tech

- [x] Put in sticky Discord logo in the right buttom of the website

## Responsiveness

- [x] Scale to mobile phone view

**Comment by seichris** [comment]
should all be fixed now
