### ISSUE TITLE
Dapp mockup v1

### ISSUE THREAD

**Issue by Kisgus** [openbot-tech/core#18]
## Mock-up v1

- [x] https://www.figma.com/file/JFnuC7hohQ9wHSDcT69dMm67/openbot-v2

**Comment by seichris** [comment]
Extended DApp mockup: https://www.figma.com/file/b2WGqHffn5FDX8TWU8R4DF9L/openbot-v2-imToken-Chris?node-id=0%3A1

The goal with this one is to make crypto trading as easy as possible for people who don't trade via algos.  But rather the normal crypto wallet user.
